export const GET_CHARACTERS = 'GET_CHARACTERS'
export const GET_CHARACTER = 'GET_CHARACTER'

export const GET_EPISODES = 'GET_EPISODES'
export const GET_EPISODE = 'GET_EPISODE'

export const GET_LOCATIONS = 'GET_LOCATIONS'
export const GET_LOCATION = 'GET_LOCATION'
export const LOCATIONS_RECEIVED = 'LOCATIONS_RECEIVED'